### ISSUE TITLE
[epic] CLI

### ISSUE THREAD

**Issue by thewillyan** [thewillyan/index-hash#7]
# Problema

Gostaríamor de ter uma interface via terminal que possa receber um arquivo de entrada que contêm comandos para o banco de dados e que gere um arquivo de relatório da execução.

## O que vamos fazer

- Elaborar uma CLI para receber um arquivo de entrada
- Desenvolver um interpretator dos comandos
- Gerar um relatório de execução

## O que não vamos fazer

# História(s) de usuário

- [ ] Interpretador de comandos
- [ ] Log de execução
- [ ] Receber comandos por arquivo
- [ ] Gerar relatório após execução de comandosI
